name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.jdk.distribution }} ${{ matrix.jdk.version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        jdk:
          - { distribution: graalvm, version: 21 }
          - { distribution: adopt-hotspot,  version: 21 }
          - { distribution: semeru,  version: 21 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.jdk.version }} (${{ matrix.jdk.distribution }})
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk.version }}
          distribution: ${{ matrix.jdk.distribution }}
          cache: maven

      - name: Build and test
        run: mvn clean verify --batch-mode --no-transfer-progress
